[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

[[plugins]]
<<<<<<< HEAD
  package = "@netlify/plugin-nextjs"
=======
  package = "@netlify/plugin-nextjs"


# The following section is causing the error because it's likely defined twice
# Remove the duplicate [images] section or merge them

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Keep only one [images] section
[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]
>>>>>>> 0a260d56ce825c92bf7df5c00160f059a0b8efd6
